---
# - name: install pyyaml in pip (for reading config files)
#   pip:
#     executable: /usr/bin/pip3
#     name: pyyaml
#   when: "{{ pageserver | default('false') }}"

- name: Create start-page-server script
  copy: 
    src: start-page-server.py
    dest: /home/ubuntu/start-page-server.py 
    owner: root 
    group: root 
    mode: "0755"
  become: true
  when: pageserver is defined

- name: Copy config file
  copy: 
    src: config.yaml
    dest: /home/ubuntu/
  when: pageserver is defined

- name: Start page server
  shell: "./start-page-server.py"
  args:
    chdir: /home/ubuntu
  become: true
  when: pageserver is defined
  # to make script run in detached mode
  async: 2629800
  poll: 0

- name: Start workload
  shell: "ssh siege-eval sh workload.sh {{workload}}"
  delegate_to: localhost
  async: 2629800
  poll: 0
  when: (workload is defined) and ( workload|int > 0)

- name: Create migrate-target script
  copy: src=migrate-target.py dest=/home/ubuntu/migrate-target.py owner=root group=root mode=0755
  become: true

- name: Start rsync daemon
  command: rsync --daemon
  become: true

- name: Execute migration target script
  shell: "./migrate-target.py {{ hostvars[source].private_address }} >> migrate-target-log"
  args:
    chdir: /home/ubuntu
  become: true
  async: 2629800
  poll: 0




